### ISSUE TITLE
missing data in covariate

### ISSUE THREAD

**Issue by choon-sim** [malucalle/selbal#25]
Hi, I have an error message when running selbal.cv on a covariate column 'dog1y' with missing data.
As a quick check, selbal.cv runs fine on a covariate column 'ethnicity' **without** missing data.
```
covariate = subset(data.frame(sample_data(ps_family)), select= c( "ethnicity"))  # selbal.cv runs fine.
covariate = subset(data.frame(sample_data(ps_family)), select= c( "dog1y"))  # selbal.cv gives an error

cv_sebal <- selbal::selbal.cv(x = data.frame(phyloseq::otu_table(ps_family)), 
                              y = phyloseq::sample_data(ps_family)$wheeze, 
                             n.fold = 10, n.iter = 10, seed = 1,
                             covar = covariate )
```
The error message is: 
 _Starting the cross - validation procedure . . .Error in { : 
  task 1 failed - "Response and predictor must be vectors of the same length."_

How should I treat these missing data? The majority of my metadata have missing data.

Choon

**Comment by UVic-omics** [comment]
Hi @choon-sim !

First of all, thank you for using `selbal` package.
Missing data is not goint to be useful to do the classification; so, when you run `selval.cv` or any other function from the package, you shuld avoid elements with missing data.

**Comment by choon-sim** [comment]
Hi UVic-omics, alright I will avoid the missing data. Thanks!
