### ISSUE TITLE
user_numVar doesn't take effects

### ISSUE THREAD

**Issue by HuoJnx** [malucalle/selbal#30]
# **Basic info:**
selbal version: 0.1.0
R version: 4.1.2 (2021-11-01) -- "Bird Hippie"
Platform: Linux s5 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux

# **Issue description:**
When setting the user_numVar, it only works in selbal_res$accuracy.nvar and selbal_res$opt.nvar, but not in the real balance selection.

# **Code**
`selbal_res$accuracy.nvar`
<img width="501" alt="image" src="https://user-images.githubusercontent.com/40828030/194992054-a1c13972-f801-4a52-b21e-90085b5c4d12.png">
`selbal_res$opt.nvar`
<img width="350" alt="image" src="https://user-images.githubusercontent.com/40828030/194992077-607349d2-b87e-4027-9055-1502c78d94dc.png">

```
num_var=6
selbal_res=selbal.cv(x=df_X,y=Y,n.fold = 8,n.iter = 10,user_numVar=num_var)
grid.draw(selbal_res$global.plot)
```
<img width="468" alt="image" src="https://user-images.githubusercontent.com/40828030/194986611-b214a987-5414-4761-87cb-e11cc1d11330.png">

`plot.tab(selbal_res$cv.tab)`
<img width="502" alt="image" src="https://user-images.githubusercontent.com/40828030/194986687-04ff1cbc-db42-4e64-94bc-29ca3d101075.png">

**Additional info**

I also try num_var=2, 3, 4, 6, 8, 10, 12. Only 2 and 3 took effect. When set to 2, the balance will include 2 variables. When set to 3, it will include 3 variables. But when more than 3, the number of variables selected will be fixed at 3.

user_numVar==2
<img width="693" alt="image" src="https://user-images.githubusercontent.com/40828030/194991623-98a68487-2579-400d-9942-0c0e238eb0b5.png">
user_numVar==3
<img width="688" alt="image" src="https://user-images.githubusercontent.com/40828030/194991741-9f9859c0-c6e3-48e4-b9db-be2c0da18ee6.png">
user_numVar>3
<img width="685" alt="image" src="https://user-images.githubusercontent.com/40828030/194991813-8d80ccbf-e6cb-4872-bb40-f798357c549b.png">

**Comment by HuoJnx** [comment]
# **Update**:
I also try the same code in personal computer and got the same results.
# **Basic info**:
selbal version: 0.1.0
R version: 4.1.1 (2021-08-10) -- "Kick Things"
Platform: Darwin HEs-MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101 arm64
# **Code**
`selbal_res$accuracy.nvar`
<img width="518" alt="image" src="https://user-images.githubusercontent.com/40828030/194992806-a5e9aa94-75a9-458c-9e63-5ccd096be43e.png">

```
num_var=6
selbal_res=selbal.cv(x=df_X,y=Y,n.fold = 8,n.iter = 10,user_numVar=num_var)
grid.draw(selbal_res$global.plot)
```
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/40828030/194992719-aaca8964-db19-4471-b384-2423e3215f79.png">

**Comment by Rivera5** [comment]
Hi @HuoJnx!

As we can see in `selbal_res$accuracy.nvar`, once we get a 3 component balance, the accuracy does not improve despite adding new variables. So, even if you order to the program to get a 5, 6, 7, component balance the function returns you the "optimal" one, which is the one satisfying the following restrictions:

- Balance with at most `maxV` variables or components
- Balance with the best accuracy value
- The simplest balance; that is, theh one with the lower number of components

In your case, according to `selbal_res$accuracy.nvar`, the first two conditions above select the balances with 3, 4, 5, 6, . . . variables. Nevertheless, is the third restriction, the simplest balance is the one with less number of varialbles, that is, a balance with 3 components.

I hope I have clarified a little the idea behind the balance selection, if not, let me know and we will try to clarify it

**Comment by HuoJnx** [comment]
Totally understood, thank you for your clarification. @Rivera5
